import { defineConfig } from 'astro/config'
import react from '@astrojs/react'
import mdx from '@astrojs/mdx'
import keystatic from '@keystatic/astro'

// Local-safe site value; replace with the real domain at deployment time.
// Canonical URLs, RSS links, and the sitemap all derive from it.
const SITE = 'http://127.0.0.1:4321'

// Keystatic's editor and API routes are local development tools only (the
// production editor is out of scope for this release). They are injected as
// on-demand routes, which would force the whole site to require a server
// adapter at build time, so the integration only runs under `astro dev`.
const keystaticIntegration = keystatic()
const keystaticDevOnly = {
  name: 'keystatic-dev-only',
  hooks: {
    'astro:config:setup': (options) => {
      if (options.command === 'dev') {
        return keystaticIntegration.hooks['astro:config:setup'](options)
      }
    },
  },
}

// The Keystatic editor UI loads Inter from Google Fonts at runtime. Rewrite
// that single reference to the locally packaged copy so the editor shell
// makes no request to a non-local origin. Development-only. The client
// graph is served through the optimizeDeps pre-bundle, which runs esbuild
// plugins rather than Vite transforms, so the replacement happens in both
// pipelines.
const INTER_REMOTE_URL = /https:\/\/fonts\.googleapis\.com\/css2\?family=Inter[^"']*/g

const keystaticOfflineFonts = {
  name: 'keystatic-offline-fonts',
  hooks: {
    'astro:config:setup': ({ command, updateConfig }) => {
      if (command !== 'dev') return
      updateConfig({
        vite: {
          optimizeDeps: {
            esbuildOptions: {
              plugins: [
                {
                  name: 'keystatic-local-inter-esbuild',
                  setup(build) {
                    build.onLoad({ filter: /keystatic-core-ui\.js$/ }, async (args) => {
                      const { readFile } = await import('node:fs/promises')
                      const contents = (await readFile(args.path, 'utf8')).replace(
                        INTER_REMOTE_URL,
                        '/fonts/keystatic-ui/inter.css',
                      )
                      return { contents, loader: 'js' }
                    })
                  },
                },
              ],
            },
          },
          plugins: [
            {
              name: 'keystatic-local-inter',
              enforce: 'pre',
              transform(code, id) {
                if (
                  id.includes('keystatic-core-ui.js') &&
                  code.includes('fonts.googleapis.com/css2?family=Inter')
                ) {
                  return code.replace(INTER_REMOTE_URL, '/fonts/keystatic-ui/inter.css')
                }
              },
            },
          ],
        },
      })
    },
  },
}

export default defineConfig({
  site: SITE,
  // NOTE: @astrojs/sitemap is not registered here. It generates the sitemap
  // only at build time, so the acceptance tests could not verify it against
  // the running dev server. The sitemap is generated by static routes in
  // src/pages/sitemap-*.xml.ts instead, which work identically in dev and
  // build and still exclude drafts (see the acceptance record).
  integrations: [react(), mdx(), keystaticDevOnly, keystaticOfflineFonts],
})
